# Create Zeros vs Zeros _like vs Zeros _initializer Tensor Using TensorFlow 2.0

In TensorFlow 2.0, we can create Zeros Tensor(every element in tensor are zeros) in different ways 
using tf.zeros() and tf.zeros_like() and tf.zeros_initializer().

## Create Zeros Tesnor using tf.zeros()

Creates a tensor with all elements set to zero (0)

Syntax:

tf.zeros(shape, dtype=tf.dtypes.float32, name=None) -> Return ZerosTensor

In [1]:
# Import TensorFlow 2
import tensorflow as tf

### Creates a tensor with all elements set to zero.

In [2]:
zeros_2dt = tf.zeros((2,2), dtype=tf.int32)
zeros_2dt

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [3]:
zeros_3dt = tf.zeros((2,2,4), dtype=tf.int8)
zeros_3dt

<tf.Tensor: shape=(2, 2, 4), dtype=int8, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)>

In [4]:
zeros_3dt.shape

TensorShape([2, 2, 4])

In [5]:
zeros_3dt.dtype

tf.int8

In [6]:
zeros_3dt.numpy()

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)

In [7]:
zeros_3dt.numpy().tolist()

[[[0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0]]]

## Create Zeros Tesnor using tf.zeros_like()

Creates a tensor with all elements set to zero.

Syntax:

tf.zeros_like(input, dtype=None, name=None) -> Return Zeros Tensor

#### Creates a tensor with all elements set to zero.

Initializer that generates tensors initialized to 0.

Initializers allow you to pre-specify an initialization strategy, encoded in the Initializer object, without knowing the shape and dtype of the variable being initialized.

Syntax:
	
tf.zeros_initializer()

In [9]:
def zeros_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))

In [10]:
zi_t_var= zeros_variable((2,2), tf.float32, tf.zeros_initializer())
zi_t_var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [11]:
zeros_variable((3,2,5), tf.bool, tf.zeros_initializer())

<tf.Variable 'Variable:0' shape=(3, 2, 5) dtype=bool, numpy=
array([[[False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False]]])>

In [12]:
tf.Variable(tf.zeros_initializer()((2,2), tf.float32))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>