# How to Create Constant Variable in TensorFlow 2.x 

In [4]:
# Check Tensorflow Version
import tensorflow as tf

In [2]:
tf.__version__

'2.17.0'

In [5]:
# Check GPU availability
tf.test.is_gpu_available()

False

In [7]:
# Create Integer Constant
a = tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [11]:
# Create float Constant
b = tf.constant(10.5)
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [12]:
# Create String Constant
c = tf.constant("Bhupeshwar Pathania")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'Bhupeshwar Pathania'>

In [14]:
# Create Boolean Constant
d = tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [16]:
# Create Constant Numpy Array/List/Tuple
import numpy as np

In [17]:
np_array = tf.constant(np.array([1,2,3,4]))
np_array

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [24]:
# Create 1D Constant
t_1d = tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [26]:
# Create 2D Constant
t_2d = tf.constant([1,2,3,4], shape=(2,2))
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [29]:
t_2d_1 = tf.constant([1,2,3,4], shape=(2,2), dtype = 'float32')
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [31]:
# Create N-D Constant
t_3d_1 = tf.constant([[[1,2],[2,3],[4,5]]], dtype = 'float32')
t_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [2., 3.],
        [4., 5.]]], dtype=float32)>

In [32]:
# Type of Constant
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [33]:
# Shape of Constant
t_3d_1.shape

TensorShape([1, 3, 2])

In [34]:
t_2d_1.shape

TensorShape([2, 2])

In [35]:
# Access Constant Value
t_1d.numpy()

array([1, 2, 3, 4])

In [36]:
t_1d.numpy()[0]

1

In [37]:
t_1d.numpy()[2]

3

In [38]:
# Constant Data Type
t_3d_1.dtype

tf.float32