# Create Sparse Tensor using TensorFlow 2.0

## What is Sparse Tensor?

In [ ]:
Tensor that contain mostly zero values are called sparse tensor.

When working with tensors that contain a lot of zero values, it is important to store them in a space- and time-efficient manner. 
Sparse tensors enable efficient storage and processing of tensors that contain a lot of zero values.
Sparse tensors are used extensively in encoding schemes like TF-IDF as part of data pre-processing in NLP applications and
for pre-processing images with a lot of dark pixels in computer vision applications.

Currently, sparse tensors in TensorFlow are encoded using the coordinate list (COO) format.

The COO encoding for sparse tensors is comprised of:

values: A 1D tensor with shape [N] containing all nonzero values.
indices: A 2D tensor with shape [N, rank], containing the indices of the nonzero values.
dense_shape: A 1D tensor with shape [rank], specifying the shape of the tensor.

A nonzero value in the context of a tf.SparseTensor is a value that’s not explicitly encoded.

Syntax: 

tf.sparse.SparseTensor(indices, values, dense_shape)


In [1]:
import tensorflow as tf

## Create TensorFlow Sparse Tensor

In [18]:
st1 = tf.SparseTensor(indices=[[0,3], [2,4]], values=[10,20], dense_shape=[3,10])
st1

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

## Create Sparse Tensor From Dense

In [19]:
import numpy as np 
np_array = np.array([[1,0,0,0],
                     [0,0,0,0],
                     [0,0,2,0],
                     [0,0,0,4]])
np_array

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [6]:
st2_fd = tf.sparse.from_dense(np_array)
st2_fd

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 4], shape=(3,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

## Extract the values, indices & shape of Sparse Tensor

In [9]:
st2_fd.values.numpy().tolist()

[1, 2, 4]

In [10]:
st2_fd.indices.numpy().tolist()

[[0, 0], [2, 2], [3, 3]]

In [11]:
st2_fd.dense_shape.numpy().tolist()

[4, 4]

## Sparse Tensor to Dense

If most of the elements are nonzero, then the tensor is considered dense.

In [13]:
dt_fst = tf.sparse.to_dense(st2_fd)
dt_fst

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])>

In [20]:
# Convert Dense tensor into numpy array
dt_fst.numpy()

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

## Mathematical operation on Sparse Tensor

In [15]:
st_add = tf.sparse.add(st2_fd, st2_fd)
st_add
 
print(st_add)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2 4 8], shape=(3,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


In [16]:
tf.sparse.to_dense(st_add).numpy()

array([[2, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 8]])