# Create Ones vs Ones_like vs Ones_initializer Tensor Using TensorFlow 2.0

In TensorFlow 2.0, we can create Ones Tensor(every element in tensor are ones) in different ways using tf.ones() and tf.ones_like() and tf.ones_initializer().

## Create Ones Tesnor using tf.ones()

Syntax:

tf.ones(shape, dtype=tf.dtypes.float32, name=None) -> Return Ones Tensor

In [1]:
# Import TensorFlow 2
import tensorflow as tf

### Create ones tensor

In [15]:
ones_2dt = tf.ones((2,2), tf.float32)
ones_2dt

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [3]:
ones_3dt = tf.ones((2,2,4), tf.float32)
ones_3dt

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

## Create Ones Tesnor using tf.ones_like()

Creates a tensor of all ones that has the same shape as the input

Syntax:

tf.ones_like(input, dtype=None, name=None) -> Return Ones Tensor

In [4]:
# Import TensorFlow 2
import tensorflow as tf

### Create ones tensor from input

In [9]:
cont_2dt = tf.constant([[1,2,3],[4,5,6]])
cont_2dt

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [6]:
ones_2dt_from_cont = tf.ones_like(cont_2dt, tf.float32)
ones_2dt_from_cont

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [7]:
var_2dt_from_var = tf.Variable([[1,2,3],[4,5,6]])
var_2dt_from_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [8]:
ones_2dt_from_var = tf.ones_like(var_2dt_from_var, tf.int32)
ones_2dt_from_var

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

## Create Ones Tesnor using tf.ones_initializer()

Initializer that generates tensors initialized to 1.

Initializers allow you to pre-specify an initialization strategy, encoded in the Initializer object, without knowing the shape and dtype of the variable being initialized.

Syntax:

tf.ones_initializer()

In [11]:
# Import TensorFlow 2
import tensorflow as tf

### Create ones tensor TensorFlow variable from the input

In [12]:
def ones_variable(shape, dtype, initializer):
    return tf.Variable(initializer(shape=shape, dtype=dtype))

In [13]:
ones_variable((2,2), tf.float32,  tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [14]:
ones_variable((2,3,5), tf.int32,  tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 3, 5) dtype=int32, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])>