# Create TensorFlow Variable using TensorFlow 2.X

In [ ]:
The Variable() constructor requires an initial value for the variable, which can be a Tensor of any type and shape. 
This initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. 
The value can be changed using one of the assign methods.

In [ ]:
Syntax:

tf.Variable(
initial_value=None, trainable=None, validate_shape=True, caching_device=None,
name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
synchronization=tf.VariableSynchronization.AUTO,
aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
)

## Import TensorFlow

In [1]:
import tensorflow as tf

## Create Tensor

In [4]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [3]:
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

## Get Variable Name, Shape, Data Type & convert into NumpyArray

In [5]:
a.name

'Variable:0'

In [6]:
a.shape

TensorShape([4])

In [7]:
a.dtype

tf.int32

In [8]:
a.numpy()

array([1, 2, 3, 4])

In [9]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

## Create TF using Integer, Float, String, Bool, Complex Number

In [10]:
t_f = tf.Variable([1.2,4.4,5,6])
t_f

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 4.4, 5. , 6. ], dtype=float32)>

In [11]:
t_s = tf.Variable(['a','b','c','d'])
t_s

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [12]:
t_b = tf.Variable([True, False])
t_b

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [13]:
t_cx = tf.Variable([3 + 4j])
t_cx

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+4.j])>

## Create TF from Constant TensorFlow Variable

In [14]:
t_con = tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [15]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

## Create TF Variable with different shape

In [16]:
t_2d = tf.Variable([[2,3], [4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [17]:
t_2d_2 = tf.Variable([[2,3], [4,5]], shape=(2,2), dtype='float32')
t_2d_2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [18]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [19]:
tf.reshape(a, (2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

## Get Index of highest value

In [20]:
t_2d_2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [21]:
tf.argmax(t_2d_2)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

In [22]:
tf.argmax(t_2d_2).numpy()

array([1, 1], dtype=int64)

## Viewed/convert as a tensor

In [23]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [24]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [25]:
tf.convert_to_tensor(t_2d_2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

## Change/Assign new value to tensor

In [26]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [27]:
a.assign([4,6,2,8])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8])>

## Assign Variable with another memory

In [ ]:
"""
If you use a variable like a tensor in operations, you will usually operate on the backing tensor.
 
Creating new variables from existing variables duplicates the backing tensors. Two variables will not share the same memory.
"""

In [32]:
a.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([16, 24,  8, 32])>

## Can't change shape and Data Type

In [29]:
a.assign([4,6,2,8,7])

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (4,), and the assigned value shape (5,) are incompatible.

In [30]:
a.assign([4.2,6.7,2.0,8.1])

TypeError: Cannot convert [4.2, 6.7, 2.0, 8.1] to EagerTensor of dtype int32